In [1]:
import pandas as pd
import numpy as np
from calculator import *
from numpy import random
from math import pi
import turtle as tt
import matplotlib.cm as cm
from tqdm import tqdm
import matplotlib.pyplot as plt
import statsmodels.api
import pandas as pd
import pingouin as pg
from statsmodels.tsa.stattools import *
from statsmodels.tsa.stattools import grangercausalitytests
from statsmodels.tsa.stattools import adfuller
from sklearn import linear_model

In [2]:
arsenic = pd.read_csv("data/arsenic.csv")
copper = pd.read_csv("data/copper.csv")
sulfate = pd.read_csv("data/sulfate.csv")
boron = pd.read_csv("data/boran.csv")
chloride = pd.read_csv("data/chloride.csv")
molybdenum = pd.read_csv("data/molybdenum.csv")
vanadium = pd.read_csv("data/vanadium.csv")
# iron = pd.read_csv("data/iron.csv")
# uranium = pd.read_csv("data/uranium.csv")

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/outdated/utils.py:18: OutdatedPackageWarning: The package pingouin is out of date. Your version is 0.5.1, the latest is 0.5.2.
Set the environment variable OUTDATED_IGNORE=1 to disable these warnings.
  **kwargs


In [3]:
arsenic.describe()

WellDepth         Time  SampleNumber     EntityId        LabId  \
count  2502.000000  2525.000000   2548.000000  2547.000000  2547.000000   
mean   1043.275779  1203.140198      1.000392     1.868473    19.195132   
std     923.103597   288.422318      0.019811     2.951755     8.497262   
min      20.000000     0.000000      1.000000     1.000000     1.000000   
25%     440.000000  1010.000000      1.000000     1.000000    23.000000   
50%     730.000000  1207.000000      1.000000     1.000000    23.000000   
75%    1303.000000  1425.000000      1.000000     1.000000    23.000000   
max    6211.000000  1900.000000      2.000000    16.000000    32.000000   

       ReliabilityId   LatitudeDD  LongitudeDD  ParameterCode  ParameterValue  \
count    2538.000000  2548.000000  2548.000000         2548.0     2548.000000   
mean        7.115445    30.582786   -96.897879         1000.0        2.759965   
std         1.135859     1.582541     1.847895            0.0        2.630968   
min         1.000000    27.474722  -100.214723         1000.0        0.000000   
25%         7.000000    29.026481   -98.550001         1000.0        1.170000   
50%         7.000000    30.780900   -96.660556         1000.0        2.000000   
75%         7.000000    32.016103   -95.267003         1000.0        2.040000   
max        14.000000    33.443611   -93.776667         1000.0       21.000000   

       PlusMinus  
count        0.0  
mean         NaN  
std          NaN  
min          NaN  
25%          NaN  
50%          NaN  
75%          NaN  
max          NaN

In [4]:
# arsenic_df = pre_process(arsenic,["arsenic"],thres = 2.75)
# copper_df = pre_process(copper,["copper"],thres = 4.91)
# sulfate_df = pre_process(sulfate,["sulfate"],thres = 60.34)
# boron_df = pre_process(boron,["boron"],thres = 418.79)
# chloride_df = pre_process(chloride,["chloride"],thres = 96.95)
# molybdenum_df = pre_process(molybdenum,["molybdenum"],thres = 2.87)
# vanadium_df = pre_process(vanadium,["vanadium"], thres = 3.12)
eps = 1e-5
arsenic_df = pre_process(arsenic,["arsenic"],thres = 2-eps)
copper_df = pre_process(copper,["copper"],thres = 2-eps)
sulfate_df = pre_process(sulfate,["sulfate"],thres = 28.6-eps)
boron_df = pre_process(boron,["boron"],thres = 200-eps)
chloride_df = pre_process(chloride,["chloride"],thres = 34.8-eps)
molybdenum_df = pre_process(molybdenum,["molybdenum"],thres = 1-eps)
vanadium_df = pre_process(vanadium,["vanadium"], thres = 1-eps)
# iron_df = pre_process(iron,["iron"],thres = 170-eps)
# eps=10e-5
# arsenic_df = pre_process(arsenic,["arsenic"],thres = 10/3-eps)
# copper_df = pre_process(copper,["copper"],thres = 1.3/3-eps)
# sulfate_df = pre_process(sulfate,["sulfate"],thres = 250/3-eps)
# boron_df = pre_process(boron,["boron"],thres = 5/3-eps)
# chloride_df = pre_process(chloride,["chloride"],thres = 21/3-eps)
# molybdenum_df = pre_process(molybdenum,["molybdenum"],thres = 40/3-eps)
# vanadium_df = pre_process(vanadium,["vanadium"], thres = 4/3-eps)

In [5]:
arsenic_df.head()

StateWellNumber      Date  LatitudeDD  LongitudeDD  ParameterValue  \
1329         5902805  19841221   30.888056   -96.816389            10.0   
389          3456704  19850513   32.147222   -95.104167            10.0   
1261         5855201  19880921   30.244444   -97.207222            10.0   
1290         5862303  19880927   30.096111   -97.251112            10.0   
1262         5855206  19880927   30.215834   -97.198611            10.0   

         type  
1329  arsenic  
389   arsenic  
1261  arsenic  
1290  arsenic  
1262  arsenic

In [6]:
# typess = [["zero_arsenic","moderate_arsenic",'high_arsenic'],["zero_copper","moderate_copper",'high_copper'],\
#          ["zero_sulfate","moderate_sulfate",'high_sulfate'],["zero_boran","moderate_boran",'high_boran'],\
#          ["zero_chloride","moderate_chloride",'high_chloride'],["zero_molybdenum","moderate_molybdenum",'high_molybdenum'],\
#          ["zero_vanadium","moderate_vanadium",'high_vanadium']]
typess = ["arsenic","copper","sulfate","boron","chloride","molybdenum","vanadium"]
l = [arsenic_df,copper_df,sulfate_df,boron_df,chloride_df,molybdenum_df,vanadium_df]

In [7]:
df = get_dates(copper)
df['year'] =  df['Date']/10000
df['year'] = df['year'].astype('int')
df = df[df['year']==2002]
date1 = df['Date']

df = get_dates(vanadium)
df['year'] =  df['Date']/10000
df['year'] = df['year'].astype('int')
df = df[df['year']==2002]
date2 = df['Date']

dates = np.intersect1d(date1,date2)

In [8]:
len(dates)

92

In [9]:
sum_vec=[]
for i in range(len(l)):
    l[i] = vectorize(l[i],typess[i],dates=dates)
    if i==0:
        sum_vec = l[0]
    if i>=1:
        sum_vec = add_vectorization(sum_vec,l[i])

In [10]:
## todo 
## sum_vec is a list of dataframe with len 92
## i-th dataframe contains all the objects on date i
sum_vec[1]

type          x          y
0      arsenic -94.726944  31.398889
1      arsenic -94.646667  31.386945
2      arsenic -94.840000  31.815001
3      arsenic -94.616112  31.718889
4      arsenic -94.665001  31.763889
5      arsenic -94.670556  31.438611
6      arsenic -94.552501  31.779444
7       copper -94.646667  31.386945
8       copper -94.665001  31.763889
9       copper -94.616112  31.718889
10      copper -94.726944  31.398889
11     sulfate -94.646667  31.386945
12     sulfate -94.726944  31.398889
13       boron -94.840000  31.815001
14       boron -94.665001  31.763889
15       boron -94.552501  31.779444
16       boron -94.646667  31.386945
17       boron -94.616112  31.718889
18       boron -94.726944  31.398889
19       boron -94.670556  31.438611
20  molybdenum -94.665001  31.763889
21  molybdenum -94.552501  31.779444
22  molybdenum -94.670556  31.438611
23  molybdenum -94.726944  31.398889
24  molybdenum -94.646667  31.386945
25  molybdenum -94.616112  31.718889
26  molybdenum -94.840000  31.815001
27    vanadium -94.646667  31.386945
28    vanadium -94.840000  31.815001
29    vanadium -94.665001  31.763889
30    vanadium -94.670556  31.438611
31    vanadium -94.616112  31.718889
32    vanadium -94.552501  31.779444
33    vanadium -94.726944  31.398889

In [11]:
from itertools import chain, combinations

def powerset(iterable):
    "powerset([1,2,3]) --> () (1,) (2,) (3,) (1,2) (1,3) (2,3) (1,2,3)"
    s = list(iterable)
    return chain.from_iterable(combinations(s, r) for r in range(1,len(s)+1))

In [12]:
list(powerset([1,2,3]))

[(1,), (2,), (3,), (1, 2), (1, 3), (2, 3), (1, 2, 3)]

In [13]:
    colo = list(powerset(typess))[10]
    print(colo)
    PI = []
    for date in range(len(dates)):
        if not (all(x in list(sum_vec[date]['type']) for x in list(colo))):
            print(list(sum_vec[date]['type'].unique()))

('arsenic', 'chloride')
['arsenic', 'sulfate', 'boron', 'molybdenum', 'vanadium']
['arsenic', 'copper', 'sulfate', 'boron', 'molybdenum', 'vanadium']
['arsenic', 'sulfate', 'boron', 'molybdenum', 'vanadium']
['arsenic', 'sulfate', 'boron', 'molybdenum', 'vanadium']
['arsenic', 'copper', 'molybdenum', 'vanadium']
['arsenic', 'copper', 'sulfate', 'molybdenum', 'vanadium']
['arsenic', 'copper', 'boron', 'molybdenum', 'vanadium']
['arsenic', 'copper', 'sulfate', 'molybdenum', 'vanadium']
['arsenic', 'sulfate', 'boron', 'molybdenum', 'vanadium']
['arsenic', 'sulfate', 'molybdenum', 'vanadium']
['arsenic', 'copper', 'sulfate', 'boron', 'molybdenum', 'vanadium']
['arsenic', 'sulfate', 'molybdenum', 'vanadium']
['arsenic', 'sulfate', 'molybdenum', 'vanadium']
['arsenic', 'sulfate', 'boron', 'molybdenum', 'vanadium']
['arsenic', 'boron', 'molybdenum', 'vanadium']
['arsenic', 'molybdenum', 'vanadium']
['arsenic', 'copper', 'sulfate', 'molybdenum', 'vanadium']
['arsenic', 'copper', 'molybdenum', 

In [14]:
# first find colocation pattern
thres = 0.8
patterns = []
num_colos = dict()
diff_colos = dict()
PIs = [] 
for colo in list(powerset(typess)):
    PI = []
    num_colo = []
    for date in range(len(dates)):
        if not (all(x in list(sum_vec[date]['type']) for x in list(colo))):
            PI.append(0)
            num_colo.append(0)
            continue
        arr=sum_vec[date].to_numpy()
        dic=get_dict(arr,key_idx=0)
        colo_array=get_colocations(dic,colo_type=list(colo),thres=0.001)
        if colo_array is None: 
            num_colo.append(0)
        else: 
            num_colo.append(len(colo_array))
        PI.append(get_modified_part_index(dic,colo_type=list(colo),colo_arr=colo_array))
    if np.mean(PI)>=thres:
        #print(colo)
        print("{} with PI = {}".format(str(colo),np.mean(PI)))
        PIs.append(np.mean(PI))
        patterns.append(colo)
        num_colos[str(colo)] = num_colo
        diff_colo = np.array(num_colo[1:])-np.array(num_colo[:-1])
        diff_colos[str(colo)] = diff_colo
patterns

('arsenic',) with PI = 1.0
('copper',) with PI = 0.8043478260869565
('boron',) with PI = 0.8586956521739131
('chloride',) with PI = 0.8043478260869565
('molybdenum',) with PI = 1.0
('vanadium',) with PI = 1.0


/Users/suhong/Desktop/UROP_Data/UROP/groundwater/calculator.py:124: RuntimeWarning: invalid value encountered in sqrt
  dists=np.sqrt(-2*pos_t2.dot(pos_t1.T)+np.sum(pos_t2**2,axis=1,keepdims=True)+np.sum(pos_t1**2,axis=1))


('arsenic', 'boron') with PI = 0.8399538866930172
('arsenic', 'molybdenum') with PI = 0.9831427630340674
('arsenic', 'vanadium') with PI = 0.9831427630340674
('boron', 'molybdenum') with PI = 0.8399538866930172
('boron', 'vanadium') with PI = 0.8399538866930172
('molybdenum', 'vanadium') with PI = 0.9831427630340674
('arsenic', 'boron', 'molybdenum') with PI = 0.8399538866930172
('arsenic', 'boron', 'vanadium') with PI = 0.8399538866930172
('arsenic', 'molybdenum', 'vanadium') with PI = 0.9831427630340674
('boron', 'molybdenum', 'vanadium') with PI = 0.8399538866930172
('arsenic', 'boron', 'molybdenum', 'vanadium') with PI = 0.8399538866930172


[('arsenic',),
 ('copper',),
 ('boron',),
 ('chloride',),
 ('molybdenum',),
 ('vanadium',),
 ('arsenic', 'boron'),
 ('arsenic', 'molybdenum'),
 ('arsenic', 'vanadium'),
 ('boron', 'molybdenum'),
 ('boron', 'vanadium'),
 ('molybdenum', 'vanadium'),
 ('arsenic', 'boron', 'molybdenum'),
 ('arsenic', 'boron', 'vanadium'),
 ('arsenic', 'molybdenum', 'vanadium'),
 ('boron', 'molybdenum', 'vanadium'),
 ('arsenic', 'boron', 'molybdenum', 'vanadium')]

In [15]:
len(patterns)

17

In [17]:
guo_index = "('arsenic',)"
guo = np.reshape(num_colos[guo_index],(-1,1))
guo = guo[1:]-guo[:-1]
causes = []
for colo in patterns:
    colo = str(colo)
    if colo!=guo_index:
        yin = np.reshape(num_colos[colo],(-1,1))
        yin = yin[1:]-yin[:-1]
        df = np.concatenate((guo,yin),axis=1)
        lags = select_time_lags(yin)
        results = grangercausalitytests(df, maxlag=[lags])
        if (results[lags])[0]['ssr_ftest'][1]<=0.1:
            causes.append(colo)


Granger Causality
number of lags (no zero) 8
ssr based F test:         F=0.6776  , p=0.7094  , df_denom=66, df_num=8
ssr based chi2 test:   chi2=6.8172  , p=0.5565  , df=8
likelihood ratio test: chi2=6.5516  , p=0.5857  , df=8
parameter F test:         F=0.6776  , p=0.7094  , df_denom=66, df_num=8

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=2.7312  , p=0.0349  , df_denom=78, df_num=4
ssr based chi2 test:   chi2=12.1854 , p=0.0160  , df=4
likelihood ratio test: chi2=11.4042 , p=0.0224  , df=4
parameter F test:         F=2.7312  , p=0.0349  , df_denom=78, df_num=4

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=1.0593  , p=0.3824  , df_denom=78, df_num=4
ssr based chi2 test:   chi2=4.7262  , p=0.3166  , df=4
likelihood ratio test: chi2=4.6023  , p=0.3306  , df=4
parameter F test:         F=1.0593  , p=0.3824  , df_denom=78, df_num=4

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=1.4154  , p=0.2367  , df_d

In [18]:
causes

["('boron',)",
 "('arsenic', 'boron')",
 "('boron', 'molybdenum')",
 "('boron', 'vanadium')",
 "('arsenic', 'boron', 'molybdenum')",
 "('arsenic', 'boron', 'vanadium')",
 "('boron', 'molybdenum', 'vanadium')",
 "('arsenic', 'boron', 'molybdenum', 'vanadium')"]

In [88]:
truth = [True,True,True,True,True,True,False,False]

In [89]:
dd = {"Granger": causes,"direct":truth}
ddd = pd.DataFrame(dd)
ddd

Granger  direct
0                     ('sulfate',)    True
1                       ('boron',)    True
2                    ('chloride',)    True
3           ('arsenic', 'sulfate')    True
4             ('arsenic', 'boron')    True
5          ('arsenic', 'chloride')    True
6             ('sulfate', 'boron')   False
7  ('arsenic', 'sulfate', 'boron')   False

In [41]:
yin = np.reshape(num_colos["('arsenic',)"],(-1,1))
guo = np.reshape(num_colos["('arsenic', 'boron')"],(-1,1))
yin = yin[1:]-yin[:-1]
guo = guo[1:]-guo[:-1]
df = np.concatenate((guo,yin),axis=1)

In [44]:
statsmodels.tsa.stattools.pacf(yin)

array([ 1.        , -0.12031785, -0.36482883, -0.42667997, -0.2789283 ,
        0.05482561, -0.28031614, -0.23298498, -0.15600179, -0.08770842,
       -0.12255337, -0.15625255, -0.21517877,  0.02866621, -0.34834047,
       -0.05805802, -0.20768454, -0.00341664, -0.12361388, -0.20348081])

In [43]:
grangercausalitytests(df, maxlag=10)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.3828  , p=0.5377  , df_denom=87, df_num=1
ssr based chi2 test:   chi2=0.3960  , p=0.5291  , df=1
likelihood ratio test: chi2=0.3952  , p=0.5296  , df=1
parameter F test:         F=0.3828  , p=0.5377  , df_denom=87, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=2.1224  , p=0.1261  , df_denom=84, df_num=2
ssr based chi2 test:   chi2=4.4975  , p=0.1055  , df=2
likelihood ratio test: chi2=4.3876  , p=0.1115  , df=2
parameter F test:         F=2.1224  , p=0.1261  , df_denom=84, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=1.1341  , p=0.3403  , df_denom=81, df_num=3
ssr based chi2 test:   chi2=3.6963  , p=0.2962  , df=3
likelihood ratio test: chi2=3.6208  , p=0.3054  , df=3
parameter F test:         F=1.1341  , p=0.3403  , df_denom=81, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=1.3012  , p=0.2770  , df_d

{1: ({'ssr_ftest': (0.3828354580282532, 0.5377063436681461, 87.0, 1),
   'ssr_chi2test': (0.39603668071888265, 0.5291432111496253, 1),
   'lrtest': (0.39516786713971896, 0.5295953828937852, 1),
   'params_ftest': (0.38283545802826874, 0.5377063436681409, 87.0, 1.0)},
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (2.1224168249274795, 0.12611881654702592, 84.0, 2),
   'ssr_chi2test': (4.497502319489183, 0.10553093358103073, 2),
   'lrtest': (4.387553421018822, 0.11149486861741985, 2),
   'params_ftest': (2.1224168249274706, 0.12611881654702695, 84.0, 2.0)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (1.1340927743192624, 0.34031183656112324, 81.0, 3),
   'ssr_chi2test': (3.6963023755590774, 0.2961804916942414, 3),
   'lrtest': (3.6207812003416393, 0.3054317398122672, 3),
   'params_ftest': (1.134092774319263, 0.34031183656112324, 81.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 

In [42]:
lags = select_time_lags(yin)
results = grangercausalitytests(df, maxlag=[lags])
results


Granger Causality
number of lags (no zero) 4
ssr based F test:         F=1.3012  , p=0.2770  , df_denom=78, df_num=4
ssr based chi2 test:   chi2=5.8053  , p=0.2142  , df=4
likelihood ratio test: chi2=5.6198  , p=0.2294  , df=4
parameter F test:         F=1.3012  , p=0.2770  , df_denom=78, df_num=4


{4: ({'ssr_ftest': (1.3011897365767326, 0.2769604991237684, 78.0, 4),
   'ssr_chi2test': (5.805308055496191, 0.21416743011974315, 4),
   'lrtest': (5.619827498682412, 0.22939561296419672, 4),
   'params_ftest': (1.3011897365767378, 0.2769604991237663, 78.0, 4.0)},
   array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 1., 0.]])])}

In [67]:
#get p-value of granger causality test
(results[4])[0]['ssr_ftest'][1]

0.004155445975629328

In [55]:
grangercausalitytests(df, maxlag=10)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.0535  , p=0.8176  , df_denom=87, df_num=1
ssr based chi2 test:   chi2=0.0554  , p=0.8140  , df=1
likelihood ratio test: chi2=0.0553  , p=0.8140  , df=1
parameter F test:         F=0.0535  , p=0.8176  , df_denom=87, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.2866  , p=0.7516  , df_denom=84, df_num=2
ssr based chi2 test:   chi2=0.6072  , p=0.7381  , df=2
likelihood ratio test: chi2=0.6052  , p=0.7389  , df=2
parameter F test:         F=0.2866  , p=0.7516  , df_denom=84, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.3952  , p=0.7568  , df_denom=81, df_num=3
ssr based chi2 test:   chi2=1.2882  , p=0.7319  , df=3
likelihood ratio test: chi2=1.2788  , p=0.7342  , df=3
parameter F test:         F=0.3952  , p=0.7568  , df_denom=81, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.2158  , p=0.9289  , df_d

{1: ({'ssr_ftest': (0.05350595252279672, 0.8176143835858538, 87.0, 1),
   'ssr_chi2test': (0.0553509853684104, 0.8140008070272722, 1),
   'lrtest': (0.05533397161281073, 0.8140288719265617, 1),
   'params_ftest': (0.053505952522780134, 0.8176143835858861, 87.0, 1.0)},
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (0.28656299479098546, 0.7515708324434764, 84.0, 2),
   'ssr_chi2test': (0.607240631818993, 0.7381410736743339, 2),
   'lrtest': (0.6051784269982932, 0.7389025652350032, 2),
   'params_ftest': (0.286562994790993, 0.751570832443473, 84.0, 2.0)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (0.3952327220421422, 0.7567665173112876, 81.0, 3),
   'ssr_chi2test': (1.2881659088780932, 0.7319450986083647, 3),
   'lrtest': (1.2788286724706381, 0.7341664514291393, 3),
   'params_ftest': (0.39523272204214505, 0.7567665173112876, 81.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 0.,

In [30]:
pacf = statsmodels.tsa.stattools.pacf(yin)
pacf

array([ 1.        , -0.26634513, -0.41448164, -0.27876701, -0.32812782,
       -0.07695989, -0.16502999, -0.13954905, -0.3058271 ,  0.08497297,
        0.14815018,  0.15747823, -0.29483484, -0.06697657, -0.04206294,
        0.12351361, -0.19783228, -0.06218909,  0.22208825, -0.07666888])

In [20]:
thres = 0.1
for i in range(len(pacf)):
    if abs(pacf[i])<=thres:
        return i+1

SyntaxError: 'return' outside function (162891836.py, line 4)

In [ ]:
x = np.array(num_colos["('sulfate',)"])
y = np.array(num_colos["('arsenic', 'boron', 'chloride')"])
z = np.array(num_colos["('arsenic', 'sulfate')"])
x = x[1:]-x[:-1]
y = y[1:]-y[:-1]
z = z[1:]-z[:-1]
dic = {'x':x,'y':y,'z':z} 
cov_df = pd.DataFrame(dic,columns = ['x','y','z'])
# test x y z and z y x
pg.partial_corr(data=cov_df, x='z', y='y', covar='x')

In [ ]:
patterns

In [ ]:
X = np.reshape(num_colos["('sulfate',)"],(-1,1))
y = np.reshape(num_colos["('arsenic',)"],(-1,1))
lm = linear_model.LinearRegression()
model = lm.fit(X,y)

In [ ]:
lm.score(y,X)

In [ ]:
select_time_lags(yin)

In [22]:
df = pd.DataFrame(diff_colos)

In [24]:
df.head()

('arsenic',)  ('copper',)  ('boron',)  ('chloride',)  ('molybdenum',)  \
0             5            4           5              0                5   
1            -1            0          -2              1               -1   
2            -3           -4          -4             -1               -3   
3             1            3           1              2                1   
4             0           -3           1             -2                0   

   ('vanadium',)  ('arsenic', 'boron')  ('arsenic', 'molybdenum')  \
0              5                     5                          5   
1             -1                    -2                         -1   
2             -3                    -4                         -3   
3              1                     1                          1   
4              0                     1                          0   

   ('arsenic', 'vanadium')  ('boron', 'molybdenum')  ('boron', 'vanadium')  \
0                        5                        5                      5   
1                       -1                       -2                     -2   
2                       -3                       -4                     -4   
3                        1                        1                      1   
4                        0                        1                      1   

   ('molybdenum', 'vanadium')  ('arsenic', 'boron', 'molybdenum')  \
0                           5                                   5   
1                          -1                                  -2   
2                          -3                                  -4   
3                           1                                   1   
4                           0                                   1   

   ('arsenic', 'boron', 'vanadium')  ('arsenic', 'molybdenum', 'vanadium')  \
0                                 5                                      5   
1                                -2                                     -1   
2                                -4                                     -3   
3                                 1                                      1   
4                                 1                                      0   

   ('boron', 'molybdenum', 'vanadium')  \
0                                    5   
1                                   -2   
2                                   -4   
3                                    1   
4                                    1   

   ('arsenic', 'boron', 'molybdenum', 'vanadium')  
0                                               5  
1                                              -2  
2                                              -4  
3                                               1  
4                                               1

In [32]:
dff = pd.DataFrame()
for pattern in causes:
    dff[str(pattern)] = df[str(pattern)]
dff["('arsenic',)"] = df["('arsenic',)"]

In [33]:
dff.head()

('boron',)  ('arsenic', 'boron')  ('boron', 'molybdenum')  \
0           5                     5                        5   
1          -2                    -2                       -2   
2          -4                    -4                       -4   
3           1                     1                        1   
4           1                     1                        1   

   ('boron', 'vanadium')  ('arsenic', 'boron', 'molybdenum')  \
0                      5                                   5   
1                     -2                                  -2   
2                     -4                                  -4   
3                      1                                   1   
4                      1                                   1   

   ('arsenic', 'boron', 'vanadium')  ('boron', 'molybdenum', 'vanadium')  \
0                                 5                                    5   
1                                -2                                   -2   
2                                -4                                   -4   
3                                 1                                    1   
4                                 1                                    1   

   ('arsenic', 'boron', 'molybdenum', 'vanadium')  ('arsenic',)  
0                                               5             5  
1                                              -2            -1  
2                                              -4            -3  
3                                               1             1  
4                                               1             0

In [34]:
dff.shape

(91, 9)

In [35]:
dff.to_csv("Data/diff_cause_colos.csv")

In [86]:
df.head(10)

('arsenic',)  ('copper',)  ('sulfate',)  ('boron',)  ('chloride',)  \
0             5            4             1           6              0   
1            -1           -1             0          -2              1   
2            -3           -3             0          -4             -1   
3             1            3             0           1              2   
4             0           -3             0          -1             -2   
5            -1            1            -2           1              1   
6            -1           -1             0          -2             -1   
7            -1            1             1           0              0   
8             2            0            -1           1              0   
9            -1            0             1          -1              0   

   ('arsenic', 'copper')  ('arsenic', 'sulfate')  ('arsenic', 'boron')  \
0                      4                       1                     6   
1                     -1                       0                    -2   
2                     -3                       0                    -4   
3                      3                       0                     1   
4                     -3                       0                    -1   
5                      1                      -2                     1   
6                     -1                       0                    -2   
7                      1                       1                     0   
8                      0                      -1                     1   
9                      0                       1                    -1   

   ('arsenic', 'chloride')  ('boron', 'chloride')  \
0                        0                      0   
1                        1                      1   
2                       -1                     -1   
3                        2                      2   
4                       -2                     -2   
5                        1                      1   
6                       -1                     -1   
7                        0                      0   
8                        0                      0   
9                        0                      0   

   ('arsenic', 'boron', 'chloride')  
0                                 0  
1                                 1  
2                                -1  
3                                 2  
4                                -2  
5                                 1  
6                                -1  
7                                 0  
8                                 0  
9                                 0

In [46]:
colo_PI = {"colo_pattern":patterns,"PI":PIs}

In [47]:
colo_PI_df  = pd.DataFrame(colo_PI)

In [48]:
colo_PI_df[:7]

colo_pattern        PI
0          (arsenic,)  1.000000
1           (copper,)  0.717391
2          (sulfate,)  0.782609
3            (boron,)  0.847826
4         (chloride,)  0.728261
5   (arsenic, copper)  0.715839
6  (arsenic, sulfate)  0.768116

In [49]:
colo_PI_df[7:]

colo_pattern        PI
7             (arsenic, boron)  0.829990
8          (arsenic, chloride)  0.718750
9              (copper, boron)  0.584679
10            (sulfate, boron)  0.564363
11           (boron, chloride)  0.684847
12    (arsenic, copper, boron)  0.584679
13   (arsenic, sulfate, boron)  0.564363
14  (arsenic, boron, chloride)  0.684847